import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ViewFooter from './components/footer'
import ViewMenu from './components/menu'
import ButtonBactotop from './components/buttonBactotop'
// import ScrollToTop from "react-scroll-to-top";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BAKEUDA - Home',
  description: 'Generated by create next app',
}


type Props = {
  children: React.ReactNode;
};

export default function RootLayout({
  children
}:Props) {
  return (
    <html lang="en">
        
      <body className={inter.className}>
        {/* <ScrollToTop smooth /> */}
        
        <ButtonBactotop/>
        <ViewMenu/>
         {children}
         <ViewFooter/>
        </body>
    </html>
  )
}
